### ISSUE TITLE
Ticket Logs

### ISSUE THREAD

**Issue by Gojira-D4** [Tyger-Git/Sanctuary-Support-Bot#3]
Create log when a ticket is closed.
Ability to view the logs with a command
Need a way for specific roles "Senior Mod" and higher to set a ticket to "secure" when closing it.  The sets a "defcon" number to the ticket in the DB to prevent lower Mods from being able to view the log.

**Comment by Tyger-Git** [comment]
Implemented. See discord for documentation.

Ticket's are automatically guarded by the database "ticketLevel"

/logs
/fulllogs
/popoutlogs
