### ISSUE TITLE
Ticket Buttons

### ISSUE THREAD

**Issue by Gojira-D4** [Tyger-Git/Sanctuary-Support-Bot#4]
Claim / Unclaim button - Button for a mod to claim a ticket
    When a ticket is claimed - bot automatically adds an emoji to the ticket Title and tags the ticket with the "Claimed" tag
    Button changes to "unclaim" - mod will use this when they are no longer able to work on the ticket. 
         Bot should remove the "claimed" tag and the emoji from the title.  Button changes back to "Claim"
Escalate - Modal window - drop down to select what to escalate the ticket to.
     Senior Mods
     Head Mods
     Administrators
     Content Creators
     Ketaries
     Demonly
Snippet - drop down to select what snippet to reply to the user with.  Admins should have permissions to create and modify snippets
Close - closes the ticket, select time frame of when to close the ticket.  Default 30 minutes.

**Comment by Tyger-Git** [comment]
Implemented. See discord for documentation.
