### ISSUE TITLE
Gather Staff Team Suggestions (Name & Ideas)

### ISSUE THREAD

**Issue by Lavender-Fields** [Tyger-Git/Sanctuary-Support-Bot#6]
Gojira & Lavender will reach out to the Sanctuary Staff Team regarding which aspects of ModMail and Ticketsbot they would like to see in the custom bot, alongside other ideas they would like to have overall. Will be creating a Google Doc for our team to send responses into and will forward potential ideas into the appropriate board after discussing.

**Comment by Tyger-Git** [comment]
Implemented. See discord for documentation.

"Sanctuary Support"
